spring:
  h2:
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
server:
  port: 8444
  ssl:
    key-store: springboot.p12
    key-store-password: Ethoca
    key-store-type: pkcs12
    key-alias: springboot
    key-password: Ethoca
